-- ============================================================
-- Load NBI California data into the bridges table
-- ============================================================
-- Uses a staging table to load all 123 raw columns as TEXT,
-- then maps and transforms them into the bridges schema.
-- ============================================================

-- Create staging table with all NBI columns as TEXT
DROP TABLE IF EXISTS nbi_staging;
CREATE TABLE nbi_staging (
    STATE_CODE_001 TEXT,
    STRUCTURE_NUMBER_008 TEXT,
    RECORD_TYPE_005A TEXT,
    ROUTE_PREFIX_005B TEXT,
    SERVICE_LEVEL_005C TEXT,
    ROUTE_NUMBER_005D TEXT,
    DIRECTION_005E TEXT,
    HIGHWAY_DISTRICT_002 TEXT,
    COUNTY_CODE_003 TEXT,
    PLACE_CODE_004 TEXT,
    FEATURES_DESC_006A TEXT,
    CRITICAL_FACILITY_006B TEXT,
    FACILITY_CARRIED_007 TEXT,
    LOCATION_009 TEXT,
    MIN_VERT_CLR_010 TEXT,
    KILOPOINT_011 TEXT,
    BASE_HWY_NETWORK_012 TEXT,
    LRS_INV_ROUTE_013A TEXT,
    SUBROUTE_NO_013B TEXT,
    LAT_016 TEXT,
    LONG_017 TEXT,
    DETOUR_KILOS_019 TEXT,
    TOLL_020 TEXT,
    MAINTENANCE_021 TEXT,
    OWNER_022 TEXT,
    FUNCTIONAL_CLASS_026 TEXT,
    YEAR_BUILT_027 TEXT,
    TRAFFIC_LANES_ON_028A TEXT,
    TRAFFIC_LANES_UND_028B TEXT,
    ADT_029 TEXT,
    YEAR_ADT_030 TEXT,
    DESIGN_LOAD_031 TEXT,
    APPR_WIDTH_MT_032 TEXT,
    MEDIAN_CODE_033 TEXT,
    DEGREES_SKEW_034 TEXT,
    STRUCTURE_FLARED_035 TEXT,
    RAILINGS_036A TEXT,
    TRANSITIONS_036B TEXT,
    APPR_RAIL_036C TEXT,
    APPR_RAIL_END_036D TEXT,
    HISTORY_037 TEXT,
    NAVIGATION_038 TEXT,
    NAV_VERT_CLR_MT_039 TEXT,
    NAV_HORR_CLR_MT_040 TEXT,
    OPEN_CLOSED_POSTED_041 TEXT,
    SERVICE_ON_042A TEXT,
    SERVICE_UND_042B TEXT,
    STRUCTURE_KIND_043A TEXT,
    STRUCTURE_TYPE_043B TEXT,
    APPR_KIND_044A TEXT,
    APPR_TYPE_044B TEXT,
    MAIN_UNIT_SPANS_045 TEXT,
    APPR_SPANS_046 TEXT,
    HORR_CLR_MT_047 TEXT,
    MAX_SPAN_LEN_MT_048 TEXT,
    STRUCTURE_LEN_MT_049 TEXT,
    LEFT_CURB_MT_050A TEXT,
    RIGHT_CURB_MT_050B TEXT,
    ROADWAY_WIDTH_MT_051 TEXT,
    DECK_WIDTH_MT_052 TEXT,
    VERT_CLR_OVER_MT_053 TEXT,
    VERT_CLR_UND_REF_054A TEXT,
    VERT_CLR_UND_054B TEXT,
    LAT_UND_REF_055A TEXT,
    LAT_UND_MT_055B TEXT,
    LEFT_LAT_UND_MT_056 TEXT,
    DECK_COND_058 TEXT,
    SUPERSTRUCTURE_COND_059 TEXT,
    SUBSTRUCTURE_COND_060 TEXT,
    CHANNEL_COND_061 TEXT,
    CULVERT_COND_062 TEXT,
    OPR_RATING_METH_063 TEXT,
    OPERATING_RATING_064 TEXT,
    INV_RATING_METH_065 TEXT,
    INVENTORY_RATING_066 TEXT,
    STRUCTURAL_EVAL_067 TEXT,
    DECK_GEOMETRY_EVAL_068 TEXT,
    UNDCLRENCE_EVAL_069 TEXT,
    POSTING_EVAL_070 TEXT,
    WATERWAY_EVAL_071 TEXT,
    APPR_ROAD_EVAL_072 TEXT,
    WORK_PROPOSED_075A TEXT,
    WORK_DONE_BY_075B TEXT,
    IMP_LEN_MT_076 TEXT,
    DATE_OF_INSPECT_090 TEXT,
    INSPECT_FREQ_MONTHS_091 TEXT,
    FRACTURE_092A TEXT,
    UNDWATER_LOOK_SEE_092B TEXT,
    SPEC_INSPECT_092C TEXT,
    FRACTURE_LAST_DATE_093A TEXT,
    UNDWATER_LAST_DATE_093B TEXT,
    SPEC_LAST_DATE_093C TEXT,
    BRIDGE_IMP_COST_094 TEXT,
    ROADWAY_IMP_COST_095 TEXT,
    TOTAL_IMP_COST_096 TEXT,
    YEAR_OF_IMP_097 TEXT,
    OTHER_STATE_CODE_098A TEXT,
    OTHER_STATE_PCNT_098B TEXT,
    OTHR_STATE_STRUC_NO_099 TEXT,
    STRAHNET_HIGHWAY_100 TEXT,
    PARALLEL_STRUCTURE_101 TEXT,
    TRAFFIC_DIRECTION_102 TEXT,
    TEMP_STRUCTURE_103 TEXT,
    HIGHWAY_SYSTEM_104 TEXT,
    FEDERAL_LANDS_105 TEXT,
    YEAR_RECONSTRUCTED_106 TEXT,
    DECK_STRUCTURE_TYPE_107 TEXT,
    SURFACE_TYPE_108A TEXT,
    MEMBRANE_TYPE_108B TEXT,
    DECK_PROTECTION_108C TEXT,
    PERCENT_ADT_TRUCK_109 TEXT,
    NATIONAL_NETWORK_110 TEXT,
    PIER_PROTECTION_111 TEXT,
    BRIDGE_LEN_IND_112 TEXT,
    SCOUR_CRITICAL_113 TEXT,
    FUTURE_ADT_114 TEXT,
    YEAR_OF_FUTURE_ADT_115 TEXT,
    MIN_NAV_CLR_MT_116 TEXT,
    FED_AGENCY TEXT,
    SUBMITTED_BY TEXT,
    BRIDGE_CONDITION TEXT,
    LOWEST_RATING TEXT,
    DECK_AREA TEXT
);

-- Load raw CSV into staging
\COPY nbi_staging FROM 'data/nbi_california.csv' WITH (FORMAT csv, HEADER true, NULL '');

-- Clear bridges table and insert mapped/transformed data
TRUNCATE TABLE bridges;

INSERT INTO bridges (
    structure_number,
    state_code,
    county,
    district,
    place_code,
    facility_carried,
    features_intersected,
    location_description,
    latitude,
    longitude,
    owner,
    functional_class,
    highway_system,
    year_built,
    year_reconstructed,
    total_length_m,
    deck_width_m,
    num_spans_main,
    num_spans_approach,
    max_span_length_m,
    deck_structure_type,
    main_structure_type,
    main_material,
    approach_material,
    deck_condition,
    superstructure_condition,
    substructure_condition,
    channel_condition,
    culvert_condition,
    structural_evaluation,
    deck_geometry_eval,
    waterway_adequacy,
    approach_alignment,
    adt,
    adt_year,
    truck_adt_pct,
    design_load,
    status,
    sufficiency_rating,
    health_index,
    last_inspection_date,
    data_year
)
SELECT
    TRIM(STRUCTURE_NUMBER_008),
    TRIM(STATE_CODE_001),
    TRIM(COUNTY_CODE_003),
    TRIM(HIGHWAY_DISTRICT_002),
    TRIM(PLACE_CODE_004),
    TRIM(BOTH '''' FROM TRIM(FACILITY_CARRIED_007)),
    TRIM(BOTH '''' FROM TRIM(FEATURES_DESC_006A)),
    TRIM(BOTH '''' FROM TRIM(LOCATION_009)),
    -- NBI lat format: DDMMSSHS (8 digits) -> decimal degrees
    CASE
        WHEN LAT_016 ~ '^\d{8}$' THEN
            (LEFT(LAT_016, 2)::NUMERIC)
            + (SUBSTRING(LAT_016, 3, 2)::NUMERIC / 60.0)
            + (SUBSTRING(LAT_016, 5, 2)::NUMERIC / 3600.0)
            + (SUBSTRING(LAT_016, 7, 2)::NUMERIC / 360000.0)
        ELSE NULL
    END,
    -- NBI long format: DDDMMSSHS (9 digits) -> negative decimal degrees (western hemisphere)
    CASE
        WHEN LONG_017 ~ '^\d{9}$' THEN
            -1.0 * (
                (LEFT(LONG_017, 3)::NUMERIC)
                + (SUBSTRING(LONG_017, 4, 2)::NUMERIC / 60.0)
                + (SUBSTRING(LONG_017, 6, 2)::NUMERIC / 3600.0)
                + (SUBSTRING(LONG_017, 8, 2)::NUMERIC / 360000.0)
            )
        ELSE NULL
    END,
    TRIM(OWNER_022),
    TRIM(FUNCTIONAL_CLASS_026),
    TRIM(HIGHWAY_SYSTEM_104),
    NULLIF(TRIM(YEAR_BUILT_027), '')::INTEGER,
    NULLIF(NULLIF(TRIM(YEAR_RECONSTRUCTED_106), ''), '0')::INTEGER,
    NULLIF(TRIM(STRUCTURE_LEN_MT_049), '')::NUMERIC,
    NULLIF(TRIM(DECK_WIDTH_MT_052), '')::NUMERIC,
    NULLIF(TRIM(MAIN_UNIT_SPANS_045), '')::INTEGER,
    NULLIF(TRIM(APPR_SPANS_046), '')::INTEGER,
    NULLIF(TRIM(MAX_SPAN_LEN_MT_048), '')::NUMERIC,
    TRIM(DECK_STRUCTURE_TYPE_107),
    TRIM(STRUCTURE_TYPE_043B),
    TRIM(STRUCTURE_KIND_043A),
    TRIM(APPR_KIND_044A),
    NULLIF(TRIM(DECK_COND_058), '')::INTEGER,
    NULLIF(TRIM(SUPERSTRUCTURE_COND_059), '')::INTEGER,
    NULLIF(TRIM(SUBSTRUCTURE_COND_060), '')::INTEGER,
    NULLIF(TRIM(CHANNEL_COND_061), '')::INTEGER,
    NULLIF(TRIM(CULVERT_COND_062), '')::INTEGER,
    TRIM(STRUCTURAL_EVAL_067),
    TRIM(DECK_GEOMETRY_EVAL_068),
    TRIM(WATERWAY_EVAL_071),
    TRIM(APPR_ROAD_EVAL_072),
    NULLIF(TRIM(ADT_029), '')::INTEGER,
    NULLIF(TRIM(YEAR_ADT_030), '')::INTEGER,
    NULLIF(TRIM(PERCENT_ADT_TRUCK_109), '')::NUMERIC,
    TRIM(DESIGN_LOAD_031),
    TRIM(OPEN_CLOSED_POSTED_041),
    NULL,  -- sufficiency_rating (not in this NBI export)
    NULL,  -- health_index (Caltrans-specific, not in NBI)
    TRIM(DATE_OF_INSPECT_090),
    2024   -- data year from filename
FROM nbi_staging;

-- Clean up
DROP TABLE nbi_staging;
